FROM nginx:alpine
# Remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf
# Copy custom nginx config
COPY nginx.conf /etc/nginx/conf.d/
# Copy frontend files
COPY . /usr/share/nginx/html/
# Remove backend folder to avoid copying unnecessary files to nginx
RUN rm -rf /usr/share/nginx/html/backend

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
