-- Schema definition for Gestion de Proyectos (Oracle Database)

-- Table: EQUIPO
CREATE TABLE EQUIPO (
    ID VARCHAR2(50) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    JERARQUIA VARCHAR2(100),
    DESTINO VARCHAR2(100),
    ROL VARCHAR2(100) DEFAULT 'Desarrollador',
    EMAIL VARCHAR2(255),
    CELULAR VARCHAR2(100),
    TELEFONO_TRABAJO VARCHAR2(100),
    IS_EXTERNO NUMBER(1) DEFAULT 0, -- 0 = False, 1 = True
    ACTIVO NUMBER(1) DEFAULT 1,     -- 0 = Inactivo, 1 = Activo
    MAX_PROYECTOS NUMBER DEFAULT 5,
    CREATED_AT VARCHAR2(30)
);

-- Table: PROYECTOS
CREATE TABLE PROYECTOS (
    ID VARCHAR2(50) PRIMARY KEY,
    NOMBRE VARCHAR2(255) NOT NULL,
    DESCRIPCION CLOB,
    EXPEDIENTE VARCHAR2(100),
    NOTA_SOLICITUD VARCHAR2(255),
    NOTA_SOLICITUD_PDF CLOB,          -- Base64 string for PDF
    AREA_SOLICITANTE VARCHAR2(255),
    LINK_DOCUMENTO VARCHAR2(500),
    ESTADO VARCHAR2(50) DEFAULT 'solicitud',
    PRIORIDAD VARCHAR2(50) DEFAULT 'media',
    DIFICULTAD NUMBER DEFAULT 3,
    PORCENTAJE_AVANCE NUMBER DEFAULT 0,
    SPRINT_ACTUAL VARCHAR2(100),
    PM VARCHAR2(50),                  -- References EQUIPO.ID
    LIDER_TECNICO VARCHAR2(50),       -- References EQUIPO.ID
    SCRUM_MASTER VARCHAR2(50),        -- References EQUIPO.ID
    PRODUCT_OWNER VARCHAR2(50),       -- References EQUIPO.ID
    DESARROLLADORES CLOB,             -- JSON string array of team member IDs
    FECHA_SOLICITUD VARCHAR2(10),
    FECHA_ESTIMADA_INICIO VARCHAR2(10),
    FECHA_ESTIMADA_FIN VARCHAR2(10),
    FECHA_REAL_INICIO VARCHAR2(10),
    FECHA_REAL_FIN VARCHAR2(10),
    FECHA_PRODUCCION VARCHAR2(10),
    TAGS CLOB,                        -- JSON string array of tags
    OBSERVACIONES CLOB,
    MINUTAS CLOB,                     -- JSON string array of minuta objects
    TICKETS_MANTIS CLOB,              -- JSON string array of Mantis ticket objects
    TICKETS_TAIGA CLOB,               -- JSON string array of Taiga ticket objects
    KANBAN_PINNED NUMBER(1) DEFAULT 0, -- 0 = False, 1 = True
    CREATED_AT VARCHAR2(30),
    UPDATED_AT VARCHAR2(30)
);

-- Table: HISTORIAL
CREATE TABLE HISTORIAL (
    ID VARCHAR2(50) PRIMARY KEY,
    ACCION VARCHAR2(50) NOT NULL,     -- 'create', 'update', 'delete', etc.
    ENTIDAD VARCHAR2(50) NOT NULL,    -- 'project', 'team', etc.
    ENTIDAD_ID VARCHAR2(50),
    DESCRIPCION VARCHAR2(1000) NOT NULL,
    TIMESTAMP VARCHAR2(30) NOT NULL
);

-- Table: CONFIGURACION (for notifications settings)
CREATE TABLE CONFIGURACION (
    CLAVE VARCHAR2(100) PRIMARY KEY,
    VALOR VARCHAR2(4000) NOT NULL
);

-- Table: USUARIOS (authentication & roles - separate from EQUIPO)
CREATE TABLE USUARIOS (
    ID VARCHAR2(50) PRIMARY KEY,
    DNI VARCHAR2(20) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    ROL_SISTEMA VARCHAR2(20) DEFAULT 'lectura',
    EQUIPO_ID VARCHAR2(50),
    NOMBRE_DISPLAY VARCHAR2(200),
    ACTIVO NUMBER(1) DEFAULT 1,
    ULTIMO_LOGIN VARCHAR2(30),
    INTENTOS_FALLIDOS NUMBER DEFAULT 0,
    BLOQUEADO_HASTA VARCHAR2(30),
    DEBE_CAMBIAR_PASSWORD NUMBER(1) DEFAULT 1,
    CREATED_AT VARCHAR2(30),
    UPDATED_AT VARCHAR2(30),
    CONSTRAINT FK_USUARIO_EQUIPO FOREIGN KEY (EQUIPO_ID) REFERENCES EQUIPO(ID)
);

-- Table: SESIONES (active sessions for token revocation)
CREATE TABLE SESIONES (
    ID VARCHAR2(50) PRIMARY KEY,
    USUARIO_ID VARCHAR2(50) NOT NULL,
    TOKEN_HASH VARCHAR2(255) NOT NULL,
    IP_ADDRESS VARCHAR2(45),
    USER_AGENT VARCHAR2(500),
    EXPIRES_AT VARCHAR2(30) NOT NULL,
    CREATED_AT VARCHAR2(30),
    CONSTRAINT FK_SESION_USUARIO FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID)
);

-- Table: AUDIT_LOG (access audit trail)
CREATE TABLE AUDIT_LOG (
    ID VARCHAR2(50) PRIMARY KEY,
    USUARIO_ID VARCHAR2(50),
    ACCION VARCHAR2(100) NOT NULL,
    DETALLE VARCHAR2(1000),
    IP_ADDRESS VARCHAR2(45),
    TIMESTAMP VARCHAR2(30) NOT NULL
);
